## Code for importing data

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from scipy import stats
from scipy.special import factorial
import scipy.optimize as opt
from scipy.optimize import fsolve

In [3]:
ro_skip = []
for i in range(0,1000):
    skip0 = 0 + i*12
    skip1 = 1 + i*12
    skip2 = 2 + i*12
    ro_skip.append(skip0)
    ro_skip.append(skip1)
    ro_skip.append(skip2)


data = pd.read_table('evrecWWmu.dat',skiprows=ro_skip,delim_whitespace=True, names=['M.C.N', 'Unknown1', 'Unknown2', 'Unknown3','Unknown4','Unknown5','Px','Py','Pz','E','M','Unknown6','Unknown7'])

## Cutting the unnecessary values ##
data = data.loc[:, ~data.columns.isin(['Unknown1', 'Unknown2', 'Unknown3', 'Unknown4', 'Unknown5', 'Unknown6', 'Unknown7'])]
data

      M.C.N         Px         Py           Pz            E             M
0      2212  -0.121187  -0.107579  6441.689670  6441.689740  9.382720e-01
1      2212   0.002975   0.016852 -6040.814950  6040.815020  9.382720e-01
2        93   0.118212   0.090726  -400.874725   517.495236  3.272625e+02
3        24 -16.241844 -60.069347  -403.188810   415.793605  8.031800e+01
4       -24  16.360056  60.160073     2.314085   101.701632  8.031800e+01
...     ...        ...        ...          ...          ...           ...
8995    -24 -47.147039 -84.337639    64.643653   141.299199  8.031800e+01
8996    -14  27.185437  94.311133   383.002563   395.379060  4.672031e-06
8997     13  19.663434  -9.560594    36.150860    42.248686  1.056600e-01
8998     14 -10.673811   1.939353    44.084532    45.399750  5.331201e-07
8999    -13 -36.473228 -86.276992    20.559122    95.899449  1.056600e-01

[9000 rows x 6 columns]

In [4]:
## Locating an event ##
event_name = {}
for x in range(1,1001):
    event_name["event{0}".format(x)] = ()

In [5]:
start_point = 0
end_point = 9

for name in event_name:
            
        globals()[name] = data.iloc[start_point:end_point].reset_index(drop=True)
        
        start_point = start_point + 9        
        end_point = start_point +9

In [6]:
## event(n) gives the nth event, 65th event is: ##

event65

   M.C.N         Px         Py           Pz            E             M
0   2212  -0.491426  -1.183024  4308.709000  4308.709290  9.382720e-01
1   2212   0.002820   0.000344 -6494.517400  6494.517470  9.382720e-01
2     93   0.488606   1.182680  2185.808400  2196.773240  2.192092e+02
3     24 -35.079644  17.663384   457.426468   466.082108  8.031800e+01
4    -24  35.568250 -16.480705  1728.381930  1730.691130  8.031800e+01
5    -14  17.494827 -11.622589    49.962185    54.197541  5.331201e-07
6     13 -52.574470  29.285973   407.464283   411.884567  1.056600e-01
7     14  -6.194364  25.655073   786.497137   786.939832  1.182848e-05
8    -13  41.762614 -42.135778   941.884794   943.751300  1.056600e-01